### ISSUE TITLE
Is there an update to ReactKitCatalog coming before Xcode 7 GM?

### ISSUE THREAD

**Issue by damianesteban** [ReactKit/ReactKitCatalog#10]
I was just curious.  If not, no big deal.  I've become interested in ReactKit lately and would like to try it out with my Xcode 7 / iOS 9 project with RealmSwift.

**Comment by inamiy** [comment]
Hi, I just updated code to current Xcode 7 Beta 6.
Please check https://github.com/ReactKit/ReactKitCatalog/commit/1731a11c0ad6f459b4ddc43f28d9f023ab4915a7.

**Comment by damianesteban** [comment]
Thanks.
